# Generated by Django 4.1.6 on 2023-02-08 18:09

import Posts.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=32767, validators=[functools.partial(Posts.models.minimum_length_validator, *(), **{'minimum': 10})]),
        ),
    ]
