"""
Django settings for OrangePiDjango project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from os import getenv
from django.utils.translation import gettext_noop

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Folder, which shared across multiple apps
SHARED_DIR = BASE_DIR / 'shared'

SECRET_KEY = getenv('SECRET_KEY')

DEBUG = bool(getenv('DEBUG', False))

ALLOWED_HOSTS = [
    '192.168.0.3',
    'articha.tplinkdns.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'AuthApp.apps.Config',
    'Posts.apps.Config',
    'Forum.apps.Config'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'AuthApp.middleware.themeCookieCheck.ThemeCookieCheckMiddleware'
]

ROOT_URLCONF = 'OrangePiDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'AuthApp.context_processors.themes_available_constant'
            ],
        },
    },
]

WSGI_APPLICATION = 'OrangePiDjango.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': SHARED_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'AuthApp.User'

# Allows using decorator @login_required
LOGIN_URL = '/'

LOCALE_PATHS = (BASE_DIR / 'locales', )

LANGUAGES = [
    ('en', 'English'),
    ('ru', 'Russian')
]

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = 'static/'

STATICFILES_DIRS = (
    BASE_DIR / 'static',
)


MEDIA_ROOT = 'shared/storage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# >> Custom variables
# =============================================================================

THEMES_AVAILABLE = {
    gettext_noop('White'): 'white.css',
    gettext_noop('Dark'): 'dark.css'
}

# Hardcoded in templates/base.html to load css based on theme
THEMES_COOKIE_NAME = 'selectedTheme'

THEMES_DEFAULT_THEME = gettext_noop('Dark')

